### ISSUE TITLE
Footer columns alignment

### ISSUE THREAD

**Issue by mttymtt** [franvelasco/franvelasco.github.io#3]
Hi Fran, 

I just wanted to make a suggestion regarding the alignment of your posts in your footer.

In the screenshot below, you'll notice how the year sections don't align once it flows into the second column.

<img width="1583" alt="Screen Shot 2020-06-27 at 11 27 23 AM_02" src="https://user-images.githubusercontent.com/10723688/85925955-d43bff00-b869-11ea-9c94-2703cd49861f.png">

One way around this is to ditch your top and bottom margins that wrap your `.footer-columns ul` and instead just apply a transparent border to create a *faux* margin.

```
.footer-columns ul {
    margin: 0;
    border-top: 1em solid transparent;
}
```

Although, as I'm writing this I'm realizing another approach would be to only add top padding.

```
.footer-columns ul {
    margin: 0;
    padding-top: 1em;
}
```

Any way, that should fix that alignment issue happening in your footer!

**Comment by franvelasco** [comment]
Thanks a ton, Matt! 

That alignment has made me literally crazy these last few days. I’m going to use that code to fix that as soon as possible.

I guess it’s because of an unclean code to show the posts in the footer but it took me a long time to make a block with the year and the listed posts so it doesn’t broke when it flowed into the second column. And I still don’t know why it doesn’t automatically align at the top. Your trick should be enough for the newbie coder I am haha.

Thanks!!

**Comment by franvelasco** [comment]
I guess it’s fixed now, although I can only try it in an iPad right now.

![fixed columns top alignment](https://user-images.githubusercontent.com/43668113/85948763-dcbc3480-b952-11ea-9d29-e7c2990cba3b.jpeg)

Thanks again, Matt!
